# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:/gitHubDesktop/shapeTest/qt_win/shape_win.ui'
#
# Created: Tue Sep 19 17:51:55 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_shapeToolWin(object):
    def setupUi(self, shapeToolWin):
        shapeToolWin.setObjectName("shapeToolWin")
        shapeToolWin.resize(701, 458)
        self.centralwidget = QtGui.QWidget(shapeToolWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.shapeToolGroupBox = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.shapeToolGroupBox.setFont(font)
        self.shapeToolGroupBox.setObjectName("shapeToolGroupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.shapeToolGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shapeToolListWidget = QtGui.QListWidget(self.shapeToolGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapeToolListWidget.sizePolicy().hasHeightForWidth())
        self.shapeToolListWidget.setSizePolicy(sizePolicy)
        self.shapeToolListWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.shapeToolListWidget.setFont(font)
        self.shapeToolListWidget.setObjectName("shapeToolListWidget")
        QtGui.QListWidgetItem(self.shapeToolListWidget)
        QtGui.QListWidgetItem(self.shapeToolListWidget)
        self.horizontalLayout.addWidget(self.shapeToolListWidget)
        self.shapeToolStackedWidget = QtGui.QStackedWidget(self.shapeToolGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapeToolStackedWidget.sizePolicy().hasHeightForWidth())
        self.shapeToolStackedWidget.setSizePolicy(sizePolicy)
        self.shapeToolStackedWidget.setObjectName("shapeToolStackedWidget")
        self.blendShapeTargetPage = QtGui.QWidget()
        self.blendShapeTargetPage.setObjectName("blendShapeTargetPage")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.blendShapeTargetPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.blendShapeTargetPage)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.blendShapeTargetNameTreeWidget = QtGui.QTreeWidget(self.blendShapeTargetPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeTargetNameTreeWidget.setFont(font)
        self.blendShapeTargetNameTreeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.blendShapeTargetNameTreeWidget.setObjectName("blendShapeTargetNameTreeWidget")
        self.horizontalLayout_4.addWidget(self.blendShapeTargetNameTreeWidget)
        self.blendShapeTargetSelectPushButton = QtGui.QPushButton(self.blendShapeTargetPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendShapeTargetSelectPushButton.sizePolicy().hasHeightForWidth())
        self.blendShapeTargetSelectPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeTargetSelectPushButton.setFont(font)
        self.blendShapeTargetSelectPushButton.setObjectName("blendShapeTargetSelectPushButton")
        self.horizontalLayout_4.addWidget(self.blendShapeTargetSelectPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.blendShapeTargetLinkPushButton = QtGui.QPushButton(self.blendShapeTargetPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendShapeTargetLinkPushButton.sizePolicy().hasHeightForWidth())
        self.blendShapeTargetLinkPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeTargetLinkPushButton.setFont(font)
        self.blendShapeTargetLinkPushButton.setObjectName("blendShapeTargetLinkPushButton")
        self.horizontalLayout_2.addWidget(self.blendShapeTargetLinkPushButton)
        self.blendShapeTargetNoPushButton = QtGui.QPushButton(self.blendShapeTargetPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendShapeTargetNoPushButton.sizePolicy().hasHeightForWidth())
        self.blendShapeTargetNoPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeTargetNoPushButton.setFont(font)
        self.blendShapeTargetNoPushButton.setObjectName("blendShapeTargetNoPushButton")
        self.horizontalLayout_2.addWidget(self.blendShapeTargetNoPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.shapeToolStackedWidget.addWidget(self.blendShapeTargetPage)
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.blendShapeImportPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendShapeImportPushButton.sizePolicy().hasHeightForWidth())
        self.blendShapeImportPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeImportPushButton.setFont(font)
        self.blendShapeImportPushButton.setObjectName("blendShapeImportPushButton")
        self.horizontalLayout_3.addWidget(self.blendShapeImportPushButton)
        self.blendShapeExportPushButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendShapeExportPushButton.sizePolicy().hasHeightForWidth())
        self.blendShapeExportPushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.blendShapeExportPushButton.setFont(font)
        self.blendShapeExportPushButton.setObjectName("blendShapeExportPushButton")
        self.horizontalLayout_3.addWidget(self.blendShapeExportPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.shapeToolStackedWidget.addWidget(self.page)
        self.horizontalLayout.addWidget(self.shapeToolStackedWidget)
        self.verticalLayout.addWidget(self.shapeToolGroupBox)
        shapeToolWin.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(shapeToolWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 23))
        self.menubar.setObjectName("menubar")
        shapeToolWin.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(shapeToolWin)
        self.statusbar.setObjectName("statusbar")
        shapeToolWin.setStatusBar(self.statusbar)

        self.retranslateUi(shapeToolWin)
        self.shapeToolStackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.shapeToolListWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.shapeToolStackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(shapeToolWin)

    def retranslateUi(self, shapeToolWin):
        shapeToolWin.setWindowTitle(QtGui.QApplication.translate("shapeToolWin", "Shape Tool Window", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("shapeToolWin", "                    Some Tool For Maya Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeToolGroupBox.setTitle(QtGui.QApplication.translate("shapeToolWin", "Shape Tool", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.shapeToolListWidget.isSortingEnabled()
        self.shapeToolListWidget.setSortingEnabled(False)
        self.shapeToolListWidget.item(0).setText(QtGui.QApplication.translate("shapeToolWin", "BlendShape Target", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeToolListWidget.item(1).setText(QtGui.QApplication.translate("shapeToolWin", "blendShape Import/Export", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeToolListWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(QtGui.QApplication.translate("shapeToolWin", "If you delete the targets for blendShape , this tool can help you to find it", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeTargetNameTreeWidget.headerItem().setText(0, QtGui.QApplication.translate("shapeToolWin", "BlendShape Node", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeTargetSelectPushButton.setText(QtGui.QApplication.translate("shapeToolWin", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeTargetLinkPushButton.setText(QtGui.QApplication.translate("shapeToolWin", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeTargetNoPushButton.setText(QtGui.QApplication.translate("shapeToolWin", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("shapeToolWin", "Import the targets shape or export", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeImportPushButton.setText(QtGui.QApplication.translate("shapeToolWin", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.blendShapeExportPushButton.setText(QtGui.QApplication.translate("shapeToolWin", "Export", None, QtGui.QApplication.UnicodeUTF8))

